### ISSUE TITLE
youtube-dlp下载报错

### ISSUE THREAD

**Issue by Jonathan52306** [666wcy/ARPT-Bot#33]
发送命令
`/video https://www.youtube.com/watch?v=l2l5sBLhUCY`
报错
`无法获取视频信息:
'entries'`
后台日志为
`object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 217, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.8/dist-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
TypeError: object NoneType can't be used in 'await' expression`

**Comment by 666wcy** [comment]
已修复，重启容器等待自动更新即可

**Comment by beer-on-ice** [comment]
还是有这个问题

**Comment by 666wcy** [comment]
![image](https://user-images.githubusercontent.com/40867688/148489185-a89246e1-5db7-47d6-a68c-14a53dedcfdb.png)
无法复现，请检查容器版本为最新或提供命令
